### ISSUE TITLE
Support all hooks

### ISSUE THREAD

**Issue by gregjacobs** [wezz/WebpackLifecyclePlugin#1]
Hey, first, just wanted to thank you for creating this. I was about to write pretty much exactly the same thing, but found your plugin!

Could it support all the webpack hooks? Probably just a matter of calling the callbacks with the correct arguments for the given hook.

**Comment by wezz** [comment]
Thanks!
It's totally possible. I'll get on it as soon as I have some time over.

**Comment by wezz** [comment]
I've added all the hooks in the documentation but I haven't tested the new code.
Please let me know if there are any issues
